* Emacs Org Babel LilyPond Mode
** Purpose

Enable Emacs Org-Babel mode to be used in a LilyPond Score Generation
Setting.

** Features
 1. Optional Automated LilyPond Compilation following the "Tangling" of
    a "Literate Org LilyPond" file
 2. Optional Automated display of resultant Musical Score
 3. Optional Automated playing of the resultant MIDI file

** Use
Hitting C-c C-c within a lilypond block inatiates tangling of all
lilypond blocks. Depending on the feature settings, ob-lilypond will 
then either display a pdf of the score, play the generated midi file,
or both.

Hitting C-c C-c t (org-babel-tangle) will tangle blocks (where tangle
is not disabled), but will not perform the additional options.

** Setup (add to emacs init file)
The Files need to be downloaded to your relevant dotfiles directory
and something similar to the following placed in your Emacs init file...

#+BEGIN_SRC emacs-lisp

(add-to-list 'load-path
             (concat dotfiles-dir  "ob-lilypond/lib"))
(require 'ob-lilypond)

#+END_SRC

